package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julian Gato
 */
public class ConsProveedorInternalFrame extends javax.swing.JInternalFrame {

    public Controlador.GestorProveedorControl gestorproveedorControl;
    private DefaultTableModel tabla;
    public ConsProveedorInternalFrame() {
        initComponents();
        gestorproveedorControl= new Controlador.GestorProveedorControl(this);
        String titulosTabla[]={"Identificacion","","Nombres","Direccion","Telefono",};
        tabla=new DefaultTableModel(null,titulosTabla);
        tbl_datos.setModel(tabla);
        tbl_datos.getColumnModel().getColumn(1).setMaxWidth(0);
        tbl_datos.getColumnModel().getColumn(1).setMinWidth(0);
        tbl_datos.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        tbl_datos.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
        btn_buscar.addActionListener(gestorproveedorControl);
        btn_cerrar.addActionListener(gestorproveedorControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdb_identificacion = new javax.swing.JRadioButton();
        rdb_nombre = new javax.swing.JRadioButton();
        rdb_todos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txt_valor = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        btn_cerrar = new javax.swing.JButton();

        setTitle("Consultar Proveedores");

        buttonGroup1.add(rdb_identificacion);
        rdb_identificacion.setText("Identificacion");

        buttonGroup1.add(rdb_nombre);
        rdb_nombre.setText("Nombre");

        buttonGroup1.add(rdb_todos);
        rdb_todos.setText("Todos");

        jLabel1.setText("Valor a buscar:");

        btn_buscar.setText("Buscar");
        btn_buscar.setName("BuscarBtn"); // NOI18N

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_datos);

        btn_cerrar.setText("Cerrar");
        btn_cerrar.setName("CerrarBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cerrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdb_identificacion)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdb_nombre)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdb_todos))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_buscar))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_identificacion)
                    .addComponent(rdb_nombre)
                    .addComponent(rdb_todos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cerrar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_buscar;
    public javax.swing.JButton btn_cerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton rdb_identificacion;
    public javax.swing.JRadioButton rdb_nombre;
    public javax.swing.JRadioButton rdb_todos;
    public javax.swing.JTable tbl_datos;
    public javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
