package Vista;

import Modelo.Login;

/**
 *
 * @author Julian Gato
 */
public class PrincipalJFrame extends javax.swing.JFrame {
    RegpacienteInternalFrame regPacienteInternalFrame;
    ConsPacienteInternalFrame consPacienteInternalFrame;
    RegcupsInternalFrame regCupsInternalFrame;
    ConsCupsInternalFrame consCupsInternalFrame;
    RegProveedorInternalFrame regProveedorInternalFrame;
    ConsProveedorInternalFrame consProveedorInternalFrame;
    RegCcInternalFrame regCcInternalFrame;
    ConsCcInternalFrame consCcInternalFrame;
    RegFvInternalFrame regFvInternalFrame;
    ConsFvInternalFrame consFvInternalFrame;
    RegApInternalFrame archplanoInternalFrame;
    
    public PrincipalJFrame() {
        regPacienteInternalFrame=new RegpacienteInternalFrame();
        consPacienteInternalFrame=new ConsPacienteInternalFrame();
        regCupsInternalFrame=new RegcupsInternalFrame();
        consCupsInternalFrame=new ConsCupsInternalFrame();
        regProveedorInternalFrame=new RegProveedorInternalFrame();
        consProveedorInternalFrame=new ConsProveedorInternalFrame();
        regCcInternalFrame=new RegCcInternalFrame();
        consCcInternalFrame=new ConsCcInternalFrame();
        regFvInternalFrame=new RegFvInternalFrame();
        consFvInternalFrame=new ConsFvInternalFrame();
        archplanoInternalFrame=new RegApInternalFrame();
        add(regPacienteInternalFrame);
        add(consPacienteInternalFrame);
        add(regCupsInternalFrame);
        add(consCupsInternalFrame);
        add(regProveedorInternalFrame);
        add(consProveedorInternalFrame);
        add(regCcInternalFrame);
        add(consCcInternalFrame);
        add(regFvInternalFrame);
        add(consFvInternalFrame);
        add(archplanoInternalFrame);
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        if(Login.parametro==1){
        jmi_RegFac.setEnabled(false);
        jmi_RegPac.setEnabled(false);
        }
        if(Login.parametro==2){
        jmi_ExpAp.setEnabled(false);
        jmi_RegPro.setEnabled(false);
        jmi_RegCc.setEnabled(false);
        jmi_ConCc.setEnabled(false);
        jmi_RegCup.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_RegPac = new javax.swing.JMenuItem();
        jmi_ConPac = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmi_RegCup = new javax.swing.JMenuItem();
        jmi_ConCup = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmi_RegPro = new javax.swing.JMenuItem();
        jmi_ConPro = new javax.swing.JMenuItem();
        JMenu5 = new javax.swing.JMenu();
        jmi_RegFac = new javax.swing.JMenuItem();
        jmi_ConFac = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmi_RegCc = new javax.swing.JMenuItem();
        jmi_ConCc = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmi_ExpAp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de facturacion");
        setName("PrincipalJFrame"); // NOI18N

        jMenu1.setText("Archivo");

        jmi_Salir.setText("salir");
        jmi_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pacientes");

        jmi_RegPac.setText("Registrar");
        jmi_RegPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_RegPacActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_RegPac);

        jmi_ConPac.setText("Consultar");
        jmi_ConPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ConPacActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_ConPac);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Codigos Cups");

        jmi_RegCup.setText("Registrar");
        jmi_RegCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_RegCupActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_RegCup);

        jmi_ConCup.setText("Consultar");
        jmi_ConCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ConCupActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_ConCup);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Proveedores");

        jmi_RegPro.setText("Registrar");
        jmi_RegPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_RegProActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_RegPro);

        jmi_ConPro.setText("Consultar");
        jmi_ConPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ConProActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_ConPro);

        jMenuBar1.add(jMenu4);

        JMenu5.setText("Facturas");

        jmi_RegFac.setText("Registrar");
        jmi_RegFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_RegFacActionPerformed(evt);
            }
        });
        JMenu5.add(jmi_RegFac);

        jmi_ConFac.setText("Consultar");
        jmi_ConFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ConFacActionPerformed(evt);
            }
        });
        JMenu5.add(jmi_ConFac);

        jMenuBar1.add(JMenu5);

        jMenu6.setText("Cuenta de Cobro");

        jmi_RegCc.setText("Registrar");
        jmi_RegCc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_RegCcActionPerformed(evt);
            }
        });
        jMenu6.add(jmi_RegCc);

        jmi_ConCc.setText("Consultar");
        jmi_ConCc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ConCcActionPerformed(evt);
            }
        });
        jMenu6.add(jmi_ConCc);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Exportar");

        jmi_ExpAp.setText("Archivo Excel");
        jmi_ExpAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ExpApActionPerformed(evt);
            }
        });
        jMenu7.add(jmi_ExpAp);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmi_SalirActionPerformed

    private void jmi_RegPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_RegPacActionPerformed
        regPacienteInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_RegPacActionPerformed

    private void jmi_ConPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ConPacActionPerformed
      consPacienteInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_ConPacActionPerformed

    private void jmi_ConCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ConCupActionPerformed
      consCupsInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_ConCupActionPerformed

    private void jmi_RegCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_RegCupActionPerformed
      regCupsInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_RegCupActionPerformed

    private void jmi_RegProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_RegProActionPerformed
        regProveedorInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_RegProActionPerformed

    private void jmi_ConProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ConProActionPerformed
        consProveedorInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_ConProActionPerformed

    private void jmi_RegCcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_RegCcActionPerformed
        regCcInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_RegCcActionPerformed

    private void jmi_ConCcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ConCcActionPerformed
        consCcInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_ConCcActionPerformed

    private void jmi_RegFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_RegFacActionPerformed
        regFvInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_RegFacActionPerformed

    private void jmi_ConFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ConFacActionPerformed
        consFvInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_ConFacActionPerformed

    private void jmi_ExpApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ExpApActionPerformed
        archplanoInternalFrame.setVisible(true);
    }//GEN-LAST:event_jmi_ExpApActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmi_ConCc;
    private javax.swing.JMenuItem jmi_ConCup;
    private javax.swing.JMenuItem jmi_ConFac;
    private javax.swing.JMenuItem jmi_ConPac;
    private javax.swing.JMenuItem jmi_ConPro;
    private javax.swing.JMenuItem jmi_ExpAp;
    private javax.swing.JMenuItem jmi_RegCc;
    private javax.swing.JMenuItem jmi_RegCup;
    private javax.swing.JMenuItem jmi_RegFac;
    private javax.swing.JMenuItem jmi_RegPac;
    private javax.swing.JMenuItem jmi_RegPro;
    private javax.swing.JMenuItem jmi_Salir;
    // End of variables declaration//GEN-END:variables

}
